apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-cka
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: slow
  hostPath:
    path: /cka
