apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc-cka
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: local-storage-cka
