apiVersion: v1
kind: Service
metadata:
  name: example-loadbalancer
  namespace: default
  labels:
    app: example-app
spec:
  type: LoadBalancer
  selector:
    app: example-app
  ports:
    - port: 80          # Porta exposta pelo LoadBalancer
      targetPort: 80    # Porta no container onde o tráfego será encaminhado
      protocol: TCP

