apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-cat-black
spec:
  selector:
    matchLabels:
      app: web-cat-black
  template:
    metadata:
      labels:
        app: web-cat-black
    spec:
      containers:
      - name: web-cat-black
        image: nginx
        resources: {}
        ports:
        - containerPort: 80
