apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: roles
  name: pod-reader
rules:
- apiGroups: [""] 
  resources: ["pods", " services"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["list", "get", "watch"]

