apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  DB_HOST: mysql-service
  DB_USER: backend
---
apiVersion: v1
kind: Pod
metadata:
  name: db-pod
spec:
  containers:
  - image: nginx
    name: db-pod
    envFrom:
    - configMapRef:
        name: db-config
