apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.serviceaccount.name }}
  labels:
    {{- include "bills.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.serviceaccount.name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceaccount.name }}
    namespace: {{ .Values.application.namespace | default "default" }}
