apiVersion: v1
kind: Service
metadata:
  name: {{ include "bills.fullname" . }}
  namespace: {{ .Values.application.namespace | default "default" }}
  labels:
    {{- include "bills.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: {{ include "bills.name" . }}
