apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bills.fullname" . }}
  namespace: {{ .Values.application.namespace | default "default" }}
  labels:
    {{- include "bills.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "bills.name" . }}
  template:
    metadata:
      labels:
        {{- include "bills.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.application.image }}"
          imagePullPolicy: {{ .Values.application.imagePullPolicy }}
          ports:
            - containerPort: 80
