apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bills.fullname" . }}
  namespace: {{ .Values.application.namespace | default "default" }}
  labels:
    {{- include "bills.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range .Values.secret.data }}
  {{ .name }}: {{ .value | b64enc }}
  {{- end }}
